package org.example.dea2.entity; // This package contains entity classes, which represent tables in the database.

import javax.persistence.*; // Import for JPA annotations (Entity, Id, etc.)
import lombok.Data; // Import for Lombok annotation to generate common methods automatically
import com.fasterxml.jackson.annotation.JsonIgnore; // Import for Jackson annotation to ignore fields during serialization


@Entity
@Data // Lombok annotation to automatically generate getter, setter, equals, hashCode, and toString methods.
public class UserDetailsEntity {

    // Unique identifier for the user, auto-generated by the database (primary key).
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-generates the ID with a unique value.
    private int id;


    private String email;

    // User's password, which is ignored when the object is serialized into JSON to avoid exposing it.
    @JsonIgnore // Prevents password from being included in JSON responses for security reasons.
    private String password;


    private String Name;
}
