package org.example.dea2.entity;

import jakarta.persistence.*;
import lombok.Data;
import java.math.BigDecimal;
import java.time.LocalDate;


@Data // Lombok's annotation to generate getters, setters, toString, equals, and hashCode methods automatically
@Entity // Marks this class as a JPA entity, representing a database table
public class VehicleEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Primary key auto-generated by the database
    private int sellingAddId; // Unique identifier for the vehicle listing

    private String vehicleName;
    private String year;
    private LocalDate startDate; // Start date of the auction or selling period
    private LocalDate endDate; // End date of the auction or selling period
    private BigDecimal bidAmount; // Current bid amount for the vehicle
    private String imagePath; // Path to the image of the vehicle
    private String description;

    @ManyToOne // Many vehicles can be associated with one user
    @JoinColumn(name = "id") // Defines the foreign key column for the user in the vehicle table
    private UserDetailsEntity user; // The user who added the vehicle for auction or sale
}
